
version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: src  # If you're requirements.txt isn't in the root directory.
      - run:
          name: Run tests
          command: pytest

workflows:
  sample:
    jobs:
      - build-and-test
